# name: Deploy to main

# on:
#   push:
#     branches:
#       - main

# jobs:
#   - name: Docker login
#     uses:

#   - name: SSH into reomote server
#     uses:

#   - name: Docker pull and start
#     uses:
